config/routes.rb
Rails.application.routes.draw do
  get 'idea'     => 'pages#idea', :as => :page_idea
  get 'invest'   => 'pages#invest', :as => :page_invest
  get 'about'    => 'pages#about', :as => :page_about
  get 'legal'    => 'pages#legal', :as => :page_legal
  get 'contact'  => 'pages#contact', :as => :page_contact
  post 'contact' => 'pages#send_contact'

  match '/curl' => 'projects#total_kwh', via: :get

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords',  confirmations: 'confirmations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources 'projects', only: [:index, :show] do
    post :confirm_participation
    member do
      get :avaible_participation
    end
  end

  get  'get_pdf/:file_name' => 'investor#show', :as => :pdf_file

  resources 'subscribes', only: [:create] do
    member do
      get :confirmation
      get :unsubscribe
    end
  end

  get  'profile' => 'profiles#edit', :as => :profile
  post 'profile' => 'profiles#create_or_update', :as => :profile_ctr_or_upd
  root 'home#index'
  #get ':slug' => 'pages#show',  :as => :pages
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/partials/_footer.html.erb
<footer>
  <div class="footer-block">
    <ul class="site-links">
      <% @page_legal.page_tabs.active.each do |tab| %>
        <li><%= link_to tab.tab_name, '/legal/#'.concat(tab.slug) %></li>
      <% end %>
    </ul>
    <ul class="contact-links">
      <li><span class="icon-phone-1"></span><%= I18n.t(:main_phone) %></li>
      <li><a href="mailto:<%= I18n.t(:main_email) %>"><span class="icon-mail-2"></span><%= I18n.t(:main_email) %></a></li>
    </ul>
    <small><%= I18n.t(:copyright) %></small>
    <ul class="social-links">
      <li><a class="icon-twitter" href="http://twitter.com" target="_blank"></a></li>
      <li><a class="icon-facebook" href="http://facebook.com" target="_blank"></a></li>
    </ul>
  </div>
</footer>

app/views/partials/_funded.html.erb
<p class="default-text top-default-text"><%= I18n.t(:invest_funded_text) %></p>

<ul class="projects-list">
  <%= 'No funded projects yet.' if projects.count == 0 %>
  <% projects.each do |project| %>
    <li class="project-block finished-project" style="background-image:url('<%= project.small_foto.url(:thumb) %>')">
      <span class="project-type"><i class="<%= icon_energy(project.type_of_energe) %>"></i></span>

      <div class="project-location"><%= project.location %></div>
      <h4 class="project-name"><%= project.name %></h4>

      <div class="project-price">
        <span>Successfully funded</span>
        <%= cute_amount(project.total_amount_need) %><sup>&euro;</sup>
      </div>
      <div class="project-statistic">
        <span><%= calculate_funded(project.total_amount_need, project.invested) %>%<i>Funded</i></span>
        <canvas data-jscomp="components/projectStatistic"
                data-percentage="<%= calculate_funded(project.total_amount_need, project.invested) %>"
                class="canvas-statistic"
                width="100"
                height="100"></canvas>
      </div>
      <div class="project-statistic">
        <span><%= number_with_precision(project.irr, strip_insignificant_zeros: true, precision: 2) %>%<i>Return</i></span>
        <canvas data-jscomp="components/projectStatistic"
                data-percentage="100"
                class="canvas-statistic"
                width="100"
                height="100"></canvas>
      </div>
      <%= link_to I18n.t(:cmn_view_project), project_path(project.id), class: 'default-btn primary-btn' %>
    </li>
  <% end %>
</ul>

app/views/partials/_header.html.erb
<header>
  <div class="header-block">
    <nav>
      <div data-jscomp="components/mobileMenu">
        <span class="icon-menu menu-control" onclick="compSupport.callFunc(this, 'handleMenu', [this])"></span>
        <ul class="site-links">
          <%= nav_link I18n.t(:menu_idea), page_idea_path %>
          <%= nav_link I18n.t(:menu_invest), page_invest_path %>
          <%= nav_link I18n.t(:menu_about), page_about_path %>
          <%= nav_link I18n.t(:menu_contact), page_contact_path %>
        </ul>
      </div>
      <div data-jscomp="components/mobileMenu">
        <span class="icon-user menu-control auth-menu-control" onclick="compSupport.callFunc(this, 'handleMenu', [this])"></span>
        <ul class="auth-links">
          <li class="login-link">
            <% if current_user %>
              <%= link_to current_user.first_name, profile_path, 'class' => 'icon-font icon-user' %>
              <%= link_to 'Logout', destroy_user_session_path %>
            <% else %>
              <%#= link_to I18n.t(:menu_login), new_user_session_path %>
              <span onclick="compSupport.callFunc('#loginPopup', 'show')" class="popup-link"><%= I18n.t(:menu_login) %></span>
              <a class="popup-link" href="/users/sign_up"><%= I18n.t(:login_popup_register) %></a>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="logo">
      <a href="/"></a>
      <object data="/images/svg/ggig_logo_last.svg" type="image/svg+xml">
        <img src="/images/ggig_logo_last.png"/>
      </object>
      <span><i></i></span>
    </div>
  </div>
</header>

app/views/partials/_infographics.html.erb
<ul class="statistic-circles">
  <% unless is_my_investment_page? || is_project_page? %>
    <li>
     <div>
       <%= Investor.investor_count %>
       <span>investors</span>
     </div>
    </li>
  <% end %>

  <li>
   <div>
     <%= cute_amount(infographics_invested) %> <sup>€</sup>
     <span>invested</span>
   </div>
  </li>

  <% unless is_project_page? %>
    <li>
     <div>
       <%= infographics_projects %>
       <span>projects</span>
     </div>
    </li>
  <% end %>

  <% if is_project_page? %>
    <li>
     <div>
       <%= @project.irr %>%
       <span>average return</span>
     </div>
    </li>
  <% elsif is_my_investment_page? %>
    <li>
     <div>
       <%= infographics_average_for_user %>%
       <span>average return</span>
     </div>
    </li>
  <% else %>
    <li>
     <div>
       <%= infographics_average %>%
       <span>average return</span>
     </div>
    </li>
  <% end %>

  <% if is_project_page? %>
    <% if @project.kwh_generated[:already_generated] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= @project.kwh_generated[:kwh_interval] %>" }'>
          <p class="savedStatistic"><%= sprintf('%.2f', @project.kwh_generated[:already_generated]) %></p>
          <span>KWH generated</span>
       </div>
      </li>
    <% end %>
    <% if @project.kwh_saved[:already_saved] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= @project.kwh_saved[:kwh_interval] %>" }'>
         <p class="savedStatistic"><%= sprintf('%.2f', @project.kwh_saved[:already_saved]) %></p>
         <span>KWH saved</span>
       </div>
      </li>
    <% end %>
  <% elsif is_my_investment_page? %>
    <% if kwh_generated_for_user[:already_generated] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= kwh_generated_for_user[:kwh_interval] %>" }'>
          <p class="savedStatistic"><%= sprintf('%.2f', kwh_generated_for_user[:already_generated]) %></p>
          <span>KWH generated</span>
       </div>
      </li>
    <% end %>
    <% if kwh_saved_for_user[:already_saved] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= kwh_saved_for_user[:kwh_interval] %>" }'>
         <p class="savedStatistic"><%= sprintf('%.2f', kwh_saved_for_user[:already_saved]) %></p>
         <span>KWH saved</span>
       </div>
      </li>
    <% end %>
  <% else %>
    <% if kwh_projects_generated[:already_generated] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= kwh_projects_generated[:kwh_interval] %>" }'>
          <p class="savedStatistic"><%= sprintf('%.2f', kwh_projects_generated[:already_generated]) %></p>
          <span>KWH generated</span>
       </div>
      </li>
    <% end %>
    <% if kwh_projects_saved[:already_saved] > 0 %>
      <li>
        <div data-jscomp='components/statisticCounter' data-jscomp-config='{"stepValue": "<%= kwh_projects_saved[:kwh_interval] %>" }'>
         <p class="savedStatistic"><%= sprintf('%.2f', kwh_projects_saved[:already_saved]) %> </p>
         <span>KWH saved</span>
       </div>
      </li>
    <% end %>
  <% end %>

  <% if is_my_investment_page? %>
    <li>
     <div>
       <%= cute_amount(money_return_for_user) %> <sup>€</sup>
       <span>money return</span>
     </div>
    </li>
  <% end %>
 </ul>

app/views/partials/_login_popup.html.erb
<div  class="popup <%= 'popup_show' if params[:login] == 'true'%>" id="loginPopup" data-jscomp="components/sendFormPopup" data-jscomp-config='{"url": "/users/sign_in", "needRedirect": true}'>

  <div class="fog" onclick="compSupport.callFunc(this, 'hide')"></div>
  <div class="popup-body">
    <span class="popup-close icon-font icon-cancel" onclick="compSupport.callFunc(this, 'hide')"></span>

    <div class="popup-title"><%= I18n.t(:login_popup_title) %></div>
    <div class="popup-content">

      <%= form_for(:user, :url => session_path(:user),
                   :html => { :'data-jscomp' => 'components/validator', method: 'post' } ) do |f| %>
        <div class="message-box"></div>
        <div class="field">
          <%= f.email_field :email,
                            autofocus: true,
                            class: 'default-input',
                            placeholder: 'email',
                            required: 'true' %>
        </div>
        <div class="field">
          <%= f.password_field :password,
                                autocomplete: 'off',
                                class: 'default-input',
                                placeholder: 'password',
                                required: 'true' %>
        </div>

        <div class="field forgot-link">
          <a href="#"
             onclick="compSupport.callFunc('#forgotPassPopup', 'show')">
            <%= I18n.t(:login_popup_forgot_pswd) %>
          </a>
        </div>

        <%= f.button I18n.t(:login_popup_btn_text),
                     class: 'default-btn primary-btn',
                     type: 'button',
                     onclick: "compSupport.callFunc('#loginPopup', 'sendForm')".html_safe %>
      <% end %>

      <div class="popup-additional">
        <a href="/users/sign_up"><%= I18n.t(:login_popup_register_link) %></a>
        <p class="default-text"><%= I18n.t(:login_popup_text).html_safe %></p>
      </div>

    </div>
  </div>

</div>

app/views/partials/_my_investments.html.erb
<p class="default-text top-default-text"><%= I18n.t(:profile_my_invest_text) %></p>

<div class="my-investments">

  <h1 class="inner-page-main-title"><%= I18n.t(:profile_my_invest_title) %></h1>

  <%= render partial: 'partials/infographics' %>

  <div class="my-investments-content">
    <% if @user_projects.count > 0 %>
      <%= render 'partials/fundable', projects: @user_projects %>
    <% else %>
      <%= render 'partials/projects_slider', projects: @projects %>
    <% end %>

    <div class="view-all-projects">
      <a class="get-back icon-font icon-left-dir" href="/invest#fundable">View all Projects</a>
    </div>

  </div>

</div>

app/views/partials/_participations_confirmation_popup.html.erb
<div class="popup participation-popup participation-confirm-popup"
     id="participationsConfirmationPopup"
     data-jscomp="components/investConfirmPopup"
     data-jscomp-config='{"url": "/projects/<%= @project.id %>/confirm_participation", "showNextPopup": "#participationsThanksPopup"}'>

  <div class="fog" onclick="compSupport.callFunc(this, 'hide')"></div>
  <div class="popup-body">
    <span class="popup-close icon-font icon-cancel" onclick="compSupport.callFunc(this, 'hide')"></span>

    <div class="popup-title"><%= I18n.t(:participation_confirm_title) %></div>
    <div class="popup-content">

      <form action="" data-jscomp="components/validator">

        <input type="hidden" name="confirmCountField" id="confirmCountField"/>
        <input type="hidden" name="confirmTotalAmountField" id="confirmTotalAmountField"/>

        <div class="message-box"></div>

        <div class="section-to-print">
          <div class="name"><%= current_user.full_name %></div>
          <div class="address"><%= short_user_info %></div>
          <div class="amount left-aligned-text"><%= I18n.t(:participation_confirm_text_1, project_name: @project.name).html_safe %></div>
          <div class="info left-aligned-text"><%= I18n.t(:participation_confirm_text_2, name: current_user.full_name).html_safe %></div>
        </div>


        <div class="actions">
          <a class="default-btn" onclick="compSupport.callFunc('#participationsConfirmationPopup', 'sendForm')">
            <%= I18n.t(:participation_confirm_button) %>
          </a>
        </div>
      </form>

      <div class="additional-actions">
        <div class="get-back">
          <a class="icon-font icon-left-dir" onclick="compSupport.callFunc('#participationsPopup', 'show')"><%= I18n.t(:cmn_back) %></a></div>
      </div>

    </div>
  </div>

</div>

app/views/partials/_participations_popup.html.erb
<div class="popup participation-popup"
     id="participationsPopup"
     data-jscomp="components/popup">

  <div class="fog" onclick="compSupport.callFunc(this, 'hide')"></div>
  <div class="popup-body">
    <span class="popup-close icon-font icon-cancel" onclick="compSupport.callFunc(this, 'hide')"></span>

    <div class="popup-title"><%= I18n.t(:invest_popup_title) %></div>
    <div class="popup-content"
         id="investComp"
         data-jscomp="components/invest"
         data-jscomp-config='{"totalAmountNeeded": "<%= @project.total_amount_need %>",
         "totalAmountInvested": "<%= @project.total_amount_invested %>",
         "amountToInvest": "<%= amount_to_invest %>",
         "interestPaid": "<%= interest_paid %>",
         "projectId": "<%= @project.id %>"}'>

      <form action="" id="investForm" data-jscomp="components/validator">
        <div class="message-box"></div>

        <div class="participations-table grid">
          <div class="grid-container">
            <table>
              <tr>
                <th><%= I18n.t(:invest_popup_grid_title_1).html_safe %></th>
                <th><%= I18n.t(:invest_popup_grid_title_2).html_safe %></th>
                <th><%= I18n.t(:invest_popup_grid_title_3).html_safe %></th>
                <th></th>
              </tr>
              <tr>
                <td style="width: 40%;">
                  <div class="count-wrapper" style="position: relative;">
                    <input class="default-input count"
                           id="investCount"
                           onchange="compSupport.callFunc('#investComp', 'calculateTotal', [this])"
                           type="number"
                           min="1"
                           value="1"/>
                  </div>
                </td>
                <td style="width: 30%;"><span>€ <span class="totalAmount"><%= amount_to_invest %></span></span></td>
                <td style="width: 30%;"><span>€ <span class="amount"><%= interest_paid %></span></span></td>
                <td><span class="grid-ok-icon"></span></td>
              </tr>
            </table>
          </div>
        </div>

        <div class="actions">
          <a class="default-btn" onclick="compSupport.callFunc('#investComp', 'checkValid')">
            <%= I18n.t(:invest_participation_popup_button) %>
          </a>
        </div>
      </form>

    </div>
  </div>

</div>

app/views/partials/_participations_thanks_popup.html.erb
<div class="popup participation-popup participation-thanks-popup" id="participationsThanksPopup" data-jscomp="components/popup">

  <div class="fog" onclick="compSupport.callFunc(this, 'hide')"></div>
  <div class="popup-body">
    <span class="popup-close icon-font icon-cancel" onclick="compSupport.callFunc(this, 'hide')"></span>

    <div class="popup-title"><%= I18n.t(:participation_thanks_title) %></div>
    <div class="popup-content"
         id="investComp"
         data-jscomp="components/investThanks">

      <form action="">

        <div class="section-to-print">
          <p><%= I18n.t(:participation_thanks_text_1, name: current_user.full_name).html_safe %>,</p>
          <p><%= I18n.t(:participation_thanks_text_2).html_safe %></p>
          <div class="generated-number">
            Name: 	Global Green Energy Lease<br><br>
            IBAN:  	<%= Project::BANK_ACCOUNT %>
          </div>
          <span><%= I18n.t(:participation_thanks_text_3).html_safe %></span>
          <span><%= I18n.t(:participation_thanks_text_4) %> <a href="/contact" target="_blank">contact us</a></span>
          <span><%= I18n.t(:participation_thanks_text_5).html_safe %></span>
        </div>

      </form>

      <div class="additional-actions">
        <div class="get-pdf">
          <%= link_to_print(@project.id, current_user.id) %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/partials/_profile_settings.html.erb
<p class="default-text top-default-text"><%= I18n.t(:profile_settings_text) %></p>

<h1 class="inner-page-main-title"><%= I18n.t(:profile_settings_title) %></h1>

<%= form_for :profile,
             :html => {
                 :id => 'editProfileForm',
                 'data-jscomp' => 'components/validator',
                 :class => 'my-profile-settings-form'
             } do |f| %>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <div class="default-label">
      <%= f.label :first_name %>
      <em><%= I18n.t(:cmn_official_label) %></em>
    </div>
    <%= text_field_tag 'user[first_name]', current_user.first_name,
                       autofocus: true,
                       :'data-validator-required' => I18n.t(:error_required),
                       :placeholder => 'First name',
                       :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>


  <div class="field">
    <div class="default-label">
      <%= f.label :last_name %>
      <em><%= I18n.t(:cmn_official_label) %></em>
    </div>
    <%= text_field_tag 'user[last_name]', current_user.last_name,
                       :'data-validator-required' => I18n.t(:error_required),
                       :placeholder => 'Last name',
                       :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field">
    <%= f.label :email, :class => 'default-label' %>
    <%= text_field_tag 'user[email]', current_user.email,
                       :'data-validator-required' => I18n.t(:error_required),
                       :'data-validator-email' => I18n.t(:error_email),
                       :placeholder => 'example@mail.com',
                       :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field">
    <div class="default-label">
      <%= f.label :phone %>
      <em><%= I18n.t(:cmn_not_required) %></em>
    </div>
    <%= f.text_field :phone,
                     :value => @profile.try(:phone),
                     :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field default-checkbox">
    <div class="default-label"></div>
    <input type="checkbox" value="" name="" id="subscribe_check"/>
    <label for="subscribe_check"><span>Stay informed on new projects</span></label>
  </div>


  <div class="separator-with-text">
    <span>Additional information for investment</span>
    <hr/>
  </div>


  <div class="field birthday-field">
    <%= f.label 'Date of Birth', :class => 'default-label' %>
    <%= f.date_select :date_of_birthday,
                      :value => @profile.try(:date_of_birthday),
                      order: [:day, :month, :year],
                      start_year: 1920,
                      include_blank: true,
                      :'data-validator-required' => I18n.t(:error_required),
                      :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field country-field">
    <%= f.label :country, :class => 'default-label' %>
    <%= f.country_select :country, ['NL'],
                         :value => @profile.try(:country),
                         include_blank: true,
                         :'data-validator-required' => I18n.t(:error_required),
                         :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field address-field">
    <%= f.label :address, :class => 'default-label' %>
    <div>
      <%= f.text_field :address_street,
                       :value => @profile.try(:address_street),
                       :placeholder => 'Street',
                       :class => 'default-input' %>
      <%= f.text_field :address_num_house,
                       :value => @profile.try(:address_num_house),
                       :placeholder => 'Number',
                       :class => 'default-input small-input' %>
      <%= f.text_field :address_city,
                       :value => @profile.try(:address_city),
                       :placeholder => 'City',
                       :class => 'default-input' %>
      <%= f.text_field :adress_zip_code,
                       :value => @profile.try(:adress_zip_code),
                       :placeholder => 'Postal',
                       :class => 'default-input small-input' %>
    </div>
  </div>

  <!--<div class="field">
    <%#= f.label :name, :class => 'default-label' %>
    <%#= f.text_field :bank_account_name,
                     :value => @profile.try(:bank_account_name),
                     :'data-validator-required' => I18n.t(:error_required),
                     :placeholder => 'Bank account name',
                     :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>

  <div class="field">
    <%#= f.label :iban, :class => 'default-label' %>
    <%#= f.text_field :bank_iban_code,
                     :value => @profile.try(:bank_iban_code),
                     :'data-validator-required' => I18n.t(:error_required),
                     :placeholder => 'Iban',
                     :class => 'default-input' %>
    <span class="icon-ok">&nbsp;</span>
  </div>-->

  <div class="separator-with-text separator-with-icon">
    <div>
      <span class="icon-ok"></span>
    </div>
    <hr/>
  </div>


  <div class="actions">
    <%= f.submit 'Save', :class => 'default-btn primary-btn' %>
  </div>

<% end %>

app/views/partials/_project_descr_stat_circles.html.erb
<ul class="statistic-circles">
  <li>
    <div>
      <%= cute_amount(project.total_amount_invested) %> <sup>€</sup>
      <span><%= I18n.t(:stat_invested) %></span>
    </div>
  </li>
  <li>
    <div>
      <%= number_with_precision(project.irr, strip_insignificant_zeros: true) %>%
      <span><%= I18n.t(:stat_fixed_return) %></span>
    </div>
  </li>
  <% if project.launch %>
    <li>
      <div>
        <%= number_with_precision(project.kwh_generated, strip_insignificant_zeros: true) %>
        <span><%= I18n.t(:stat_generated) %></span>
      </div>
    </li>
  <% end %>
  <% if false #project.is_power_saved? %>
    <li>
      <div data-jscomp='components/statisticCounter'
           data-jscomp-config='{
           "stepValue": "<%= project.power_saved.kwh_every_second %>",
           "updateInterval": "1000"
           }'>
        <p class="savedStatistic"><%= saved_kwh(project.id) %></p>
        <span><%= I18n.t(:stat_saved) %></span>
      </div>
    </li>
  <% end %>
</ul>

app/views/partials/_projects_stat_circles.html.erb
<ul class="statistic-circles">
  <li>
    <div>
      50.000 <sup>€</sup>
      <span><%= I18n.t(:stat_investors) %></span>
    </div>
  </li>
  <li>
    <div>
      100 <em>MLN</em>
      <span><%= I18n.t(:stat_invested) %></span>
    </div>
  </li>
  <li>
    <div>
      32
      <span><%= I18n.t(:stat_projects) %></span>
    </div>
  </li>
  <li>
    <div>
      504.000
      <span><%= I18n.t(:stat_generated) %></span>
    </div>
  </li>
  <li>
    <div>
      6.5%
      <span><%= I18n.t(:stat_return) %></span>
    </div>
  </li>
</ul>

app/views/partials/_subscription.html.erb
<section class="subscription" id="subscription" data-jscomp="components/subscribes">
  <h2><%= I18n.t(:subscr_title) %></h2>

  <p class="default-text"><%= I18n.t(:subscr_text) %></p>

  <form action="#" method="POST" id="subscribeForm" data-jscomp="components/validator">

    <div class="updating-layer">
      <object data="../images/svg/spinner.svg" type="image/svg+xml">
        Loading...
      </object>
    </div>
    <div class="message-box"></div>

    <div>
      <div class="input-wrapper">
        <input name="subscribe[name]"
               type="text"
               class="default-input"
               placeholder="<%= I18n.t(:subscr_name_field) %>"
               required/>
      </div>
      <div class="input-wrapper">
        <input name="subscribe[email]"
               type="email"
               class="default-input"
               placeholder="<%= I18n.t(:subscr_email_field) %>"
               required/>
      </div>
    </div>

    <input type="button"
           class="default-btn primary-btn"
           value="<%= I18n.t(:subscr_submit) %>"
           id="subscribe"
           onclick="compSupport.callFunc('#subscription', 'sendForm')"/>
  </form>
</section>

app/views/partials/_trade.html.erb
<p class="default-text top-default-text"><%= I18n.t(:invest_trade_text) %></p>

<section class="grid">
  <h5 class="inner-page-sub-title"><%= I18n.t(:invest_trade_send_email).html_safe %></h5>

  <div class="grid-container">
    <table>
      <thead>
      <tr>
        <th>project name</th>
        <th>numbers of participations</th>
        <th>selling price</th>
        <th>return rate</th>
        <th>total € interest payed</th>
        <th>numbers of years left</th>
        <th>project status</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>curacao</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>
          <a href="#" onclick="compSupport.callFunc('#participationsPopup', 'show')" class="default-btn">Make offer</a>
        </td>
      </tr>
      <tr>
        <td>curacao 2</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>
          <a href="#" onclick="compSupport.callFunc('#participationsPopup', 'show')" class="default-btn">Make offer</a>
        </td>
      </tr>
      <tr>
        <td>rembrand windpark</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
      </tr>
      <tr>
        <td>sint maarten</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
        <td>€ 498.20</td>
      </tr>
      </tbody>
    </table>
  </div>

</section>

<%= render 'partials/participations_popup' %>

<%= render 'partials/subscription' %>