config/routes.rb
Rails.application.routes.draw do
  get 'idea'     => 'pages#idea', :as => :page_idea
  get 'invest'   => 'pages#invest', :as => :page_invest
  get 'about'    => 'pages#about', :as => :page_about
  get 'legal'    => 'pages#legal', :as => :page_legal
  get 'contact'  => 'pages#contact', :as => :page_contact
  post 'contact' => 'pages#send_contact'

  match '/curl' => 'projects#total_kwh', via: :get

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords',  confirmations: 'confirmations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources 'projects', only: [:index, :show] do
    post :confirm_participation
    member do
      get :avaible_participation
    end
  end

  get  'get_pdf/:file_name' => 'investor#show', :as => :pdf_file

  resources 'subscribes', only: [:create] do
    member do
      get :confirmation
      get :unsubscribe
    end
  end

  get  'profile' => 'profiles#edit', :as => :profile
  post 'profile' => 'profiles#create_or_update', :as => :profile_ctr_or_upd
  root 'home#index'
  #get ':slug' => 'pages#show',  :as => :pages
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :investors, dependent: :destroy
  has_many :projects,  -> { uniq }, through: :investors

  enum role: [:regular, :applicant, :investor]

  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true

  scope :with_investment, -> { joins(:investors).uniq }

  def full_name
    " #{self.first_name.camelcase} #{self.last_name.camelcase} "
  end
end

app/views/admin/users/_index.html.erb
<div class="index_as_table">
<table border="0" cellspacing="0" cellpadding="0" id="index_table_investors" class="index_table index" paginator="true">
  <thead>
    <tr>
      <th class="col col-user">User</th>
      <th class="col col-project">Project</th>
      <th class="col col-total_amount">Total Amount</a></th>
      <th class="col col-confirm_paid">Confirm Paid</a></th>
      <th class="col col-created_at"><a href="/admin/investors?order=created_at_desc">Created At</a></th>
      <th class="col col-actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="odd hightlightuser">
        <td class="col col-user">
          <%= link_to user.full_name, admin_user_path(user.id)%>
        </td>
        <td class="col col-actions"  colspan="5" >

        </td>
      </tr>
      <%= "<tr><td colspan=6>Don't have investment</td></tr>".html_safe unless user.investors.present? %>
      <% user.investors.each do |investor| %>
        <% status = investor.confirm_paid ? 'yes' : 'no' %>
        <tr>
          <td>

          </td>
          <td class="col col-project">
            <%= link_to investor.project.name, admin_project_path(investor.project_id)%>
          </td>
          <td class="col col-total_amount">
            <%= investor.total_amount %>
          </td>
          <td class="col col-confirm_paid">
            <span class="status_tag <%=status%>"><%=status%></span>
          </td>
          <td class="col col-created_at">
            <%= investor.created_at.strftime("%B %d, %Y %a")  %>
          </td>
          <td>
            <div class="table_actions">
              <%= link_to 'View', admin_investor_path(investor) %>
              <%= link_to 'Edit', edit_admin_investor_path(investor) %>
              <a class="delete_link member_link" data-confirm="Are you sure you want to delete this?" rel="nofollow" data-method="delete" href="/admin/investors/31">Delete</a>                            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>